---
agent_list:
- 10.11.10.33
# Use this bootstrap_url value unless you have moved the DC/OS installer assets.
bootstrap_url: http://10.11.10.32
cluster_name: dcos
exhibitor_storage_backend: static
master_discovery: static
master_list:
- 10.11.10.30
resolvers:
- 8.8.4.4
- 8.8.8.8
ssh_port: 22
ssh_user: centos
